import React, { createContext, useState, useContext, ReactNode, useMemo } from 'react';

type Language = 'en' | 'pt';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const languageData = {
    en: {
        'home.title.part1': 'Create stunning',
        'home.title.part2': 'ad creatives',
        'home.subtitle': 'Choose a project to start building your next high-impact ad.',
        'project.video.title': 'Video Ad',
        'project.video.description': 'A simple vertical video ad format.',
        'project.slider.title': 'Before & After Slider',
        'project.slider.description': 'Showcase transformations with an interactive slider.',
        'project.soccer.title': 'Video + Display Ad',
        'project.soccer.description': 'Combine a video with a static image in one creative.',
        'project.carousel.title': 'Carousel Ad',
        'project.carousel.description': 'Display multiple products or features in a swipeable format.',
        'project.cube.title': '3D Cube Ad',
        'project.cube.description': 'Engage users with an animated 3D cube showcasing different perspectives.',
        'common.backToProjects': 'Back to Projects',
        'preview.title': 'Live Preview',
        'form.title': 'Video Ad Settings',
        'form.videoUrl': 'Video URL',
        'form.videoUrlPlaceholder': 'https://...',
        'form.or': 'or',
        'form.uploadVideo': 'Upload Video',
        'form.upload': 'Upload',
        'form.settingsTitle': 'Ad Details',
        'form.size': 'Size',
        'form.brand': 'Brand Name',
        'form.caption': 'Caption Text',
        'form.hashtag': 'Hashtag',
        'form.destinationUrl': 'Destination URL',
        'form.textColor': 'Text Color',
        'form.likes': 'Likes',
        'form.comments': 'Comments',
        'form.publisher': 'Publisher Name',
        'form.verified': 'Verified Publisher',
        'form.avatar': 'Avatar Image',
        'form.export.title': 'Export',
        'form.export.html_dv360': 'Export HTML for DV360',
        'form.export.html_gam': 'Export HTML for GAM',
        'form.slider.v2.section.sizeAndMedia': 'Size & Media',
        'form.slider.v2.template': 'Template',
        'form.slider.v2.template.classic': 'Classic (Text/CTA bottom-left)',
        'form.slider.v2.template.modern': 'Modern (Text top-center)',
        'form.slider.v2.beforeImageUrl': 'Before Image URL',
        'form.slider.v2.uploadImage': 'Upload Image',
        'form.slider.v2.afterImageUrl': 'After Image URL',
        'form.slider.v2.section.slider': 'Slider Control',
        'form.slider.v2.handleStyle': 'Handle Style',
        'form.slider.v2.handleIcon': 'Handle Icon',
        'form.slider.v2.handleThickness': 'Handle Thickness',
        'form.slider.v2.dividerColor': 'Divider Color',
        'form.slider.v2.dividerWidth': 'Divider Width',
        'form.slider.v2.section.labels': 'Labels',
        'form.slider.v2.showLabels': 'Show Labels',
        'form.slider.v2.labelStyle': 'Label Style',
        'form.slider.v2.beforeLabel': '"Before" Label Text',
        'form.slider.v2.afterLabel': '"After" Label Text',
        'form.slider.v2.labelBg': 'Label Background Color',
        'form.slider.v2.labelColor': 'Label Text Color',
        'form.slider.v2.section.branding': 'Branding',
        'form.slider.v2.uploadLogo': 'Upload Logo',
        'form.slider.v2.logoPositionX': 'Logo Position (X-axis)',
        'form.slider.v2.logoPositionY': 'Logo Position (Y-axis)',
        'form.slider.v2.logoZoom': 'Logo Zoom',
        'form.slider.v2.section.cta': 'Call to Action',
        'form.slider.v2.showCta': 'Show CTA Button',
        'form.slider.v2.ctaText': 'CTA Text',
        'form.slider.v2.ctaStyle': 'CTA Style',
        'form.slider.v2.ctaBg': 'CTA Background/Border Color',
        'form.slider.v2.ctaColor': 'CTA Text Color',
        'form.slider.v2.section.text': 'Text Overlay',
        'form.slider.v2.headline': 'Headline',
        'form.slider.v2.caption': 'Caption',
        'form.slider.v2.fgColor': 'Foreground Color',
        'form.slider.v2.section.interaction': 'Interaction & Animation',
        'form.slider.v2.startPosition': 'Start Position',
        'form.slider.v2.hintAnimation': 'Hint Animation',
        'form.slider.v2.hintLoop': 'Loop Hint Animation',
        'form.slider.v2.sweepDuration': 'Sweep Duration (ms)',
        'form.slider.v2.animateZoom': 'Animate Zoom on Hover',
        'form.slider.v2.zoomLevel': 'Zoom Level',
        'form.slider.v2.zoomDuration': 'Zoom Duration (s)',
        'form.slider.v2.section.export': 'Export',
        'form.slider.v2.beforeDestinationUrl': 'Before Image Destination URL',
        'form.slider.v2.afterDestinationUrl': 'After Image Destination URL',
        'form.slider.v2.exportHtml': 'Export HTML for GAM/DV360',
        'form.slider.v2.exportGif': 'Export Demo GIF',
        'form.soccer.section.general': 'General Settings',
        'form.soccer.section.assets': 'Assets',
        'form.soccer.videoUrl': 'Video URL',
        'form.soccer.uploadVideo': 'Upload Video',
        'form.soccer.imageUrl': 'Image URL',
        'form.soccer.uploadImage': 'Upload Image',
        'form.soccer.imageHint': 'Recommended image size: {size}',
        'form.soccer.exportHtml_dv360': 'Export ZIP for DV360',
        'form.soccer.exportHtml_gam': 'Export HTML for GAM',
        'form.carousel.section.general': 'General Settings',
        'form.carousel.ctaText': 'CTA Button Text',
        'form.carousel.ctaBgColor': 'CTA Background Color',
        'form.carousel.ctaColor': 'CTA Text Color',
        'form.carousel.progressBarColor': 'Progress Bar Color',
        'form.carousel.autoPlay': 'Auto-play Slides',
        'form.carousel.playDuration': 'Auto-play Duration (s)',
        'form.carousel.section.slides': 'Slides',
        'form.carousel.addSlide': 'Add New Slide',
        'form.carousel.slide': 'Slide',
        'form.carousel.headline': 'Headline',
        'form.carousel.caption': 'Caption',
        'form.carousel.exportHtml': 'Export HTML for GAM/DV360',
        'form.cube.section.general': 'General Settings',
        'form.cube.frontImage': 'Front Face Image',
        'form.cube.sideImage': 'Side Face Image',
        'form.cube.uploadImage': 'Upload Image',
        'form.cube.rotationSpeed': 'Rotation Speed (seconds)',
        'form.cube.exportHtml': 'Export HTML Only (CDN Links)',
        'form.cube.exportZip': 'Export ZIP (HTML + Images)',
    },
    pt: {
        'home.title.part1': 'Crie criativos',
        'home.title.part2': 'de anúncios incríveis',
        'home.subtitle': 'Escolha um projeto para começar a construir seu próximo anúncio de alto impacto.',
        'project.video.title': 'Anúncio em Vídeo',
        'project.video.description': 'Um formato de anúncio de vídeo vertical simples.',
        'project.slider.title': 'Slider Antes e Depois',
        'project.slider.description': 'Mostre transformações com um controle deslizante interativo.',
        'project.soccer.title': 'Anúncio de Vídeo + Display',
        'project.soccer.description': 'Combine um vídeo com uma imagem estática em um único criativo.',
        'project.carousel.title': 'Anúncio em Carrossel',
        'project.carousel.description': 'Exiba vários produtos ou recursos em um formato que pode ser deslizado.',
        'project.cube.title': 'Anúncio em Cubo 3D',
        'project.cube.description': 'Engaje os usuários com um cubo 3D animado que exibe diferentes perspectivas.',
        'common.backToProjects': 'Voltar aos Projetos',
        'preview.title': 'Visualização ao Vivo',
        'form.title': 'Configurações do Anúncio de Vídeo',
        'form.videoUrl': 'URL do Vídeo',
        'form.videoUrlPlaceholder': 'https://...',
        'form.or': 'ou',
        'form.uploadVideo': 'Carregar Vídeo',
        'form.upload': 'Carregar',
        'form.settingsTitle': 'Detalhes do Anúncio',
        'form.size': 'Tamanho',
        'form.brand': 'Nome da Marca',
        'form.caption': 'Texto da Legenda',
        'form.hashtag': 'Hashtag',
        'form.destinationUrl': 'URL de Destino',
        'form.textColor': 'Cor do Texto',
        'form.likes': 'Curtidas',
        'form.comments': 'Comentários',
        'form.publisher': 'Nome do Editor',
        'form.verified': 'Editor Verificado',
        'form.avatar': 'Imagem do Avatar',
        'form.export.title': 'Exportar',
        'form.export.html_dv360': 'Exportar HTML para DV360',
        'form.export.html_gam': 'Exportar HTML para GAM',
        'form.slider.v2.section.sizeAndMedia': 'Tamanho & Mídia',
        'form.slider.v2.template': 'Modelo',
        'form.slider.v2.template.classic': 'Clássico (Texto/CTA inferior esquerdo)',
        'form.slider.v2.template.modern': 'Moderno (Texto superior central)',
        'form.slider.v2.beforeImageUrl': 'URL da Imagem "Antes"',
        'form.slider.v2.uploadImage': 'Carregar Imagem',
        'form.slider.v2.afterImageUrl': 'URL da Imagem "Depois"',
        'form.slider.v2.section.slider': 'Controle Deslizante',
        'form.slider.v2.handleStyle': 'Estilo do Controle',
        'form.slider.v2.handleIcon': 'Ícone do Controle',
        'form.slider.v2.handleThickness': 'Espessura do Controle',
        'form.slider.v2.dividerColor': 'Cor do Divisor',
        'form.slider.v2.dividerWidth': 'Largura do Divisor',
        'form.slider.v2.section.labels': 'Rótulos',
        'form.slider.v2.showLabels': 'Mostrar Rótulos',
        'form.slider.v2.labelStyle': 'Estilo do Rótulo',
        'form.slider.v2.beforeLabel': 'Texto do Rótulo "Antes"',
        'form.slider.v2.afterLabel': 'Texto do Rótulo "Depois"',
        'form.slider.v2.labelBg': 'Cor de Fundo do Rótulo',
        'form.slider.v2.labelColor': 'Cor do Texto do Rótulo',
        'form.slider.v2.section.branding': 'Marca',
        'form.slider.v2.uploadLogo': 'Carregar Logo',
        'form.slider.v2.logoPositionX': 'Posição do Logo (eixo X)',
        'form.slider.v2.logoPositionY': 'Posição do Logo (eixo Y)',
        'form.slider.v2.logoZoom': 'Zoom do Logo',
        'form.slider.v2.section.cta': 'Chamada para Ação',
        'form.slider.v2.showCta': 'Mostrar Botão de CTA',
        'form.slider.v2.ctaText': 'Texto do CTA',
        'form.slider.v2.ctaStyle': 'Estilo do CTA',
        'form.slider.v2.ctaBg': 'Cor de Fundo/Borda do CTA',
        'form.slider.v2.ctaColor': 'Cor do Texto do CTA',
        'form.slider.v2.section.text': 'Texto Sobreposto',
        'form.slider.v2.headline': 'Título',
        'form.slider.v2.caption': 'Legenda',
        'form.slider.v2.fgColor': 'Cor do Texto',
        'form.slider.v2.section.interaction': 'Interação & Animação',
        'form.slider.v2.startPosition': 'Posição Inicial',
        'form.slider.v2.hintAnimation': 'Animação de Dica',
        'form.slider.v2.hintLoop': 'Repetir Animação de Dica',
        'form.slider.v2.sweepDuration': 'Duração da Varredura (ms)',
        'form.slider.v2.animateZoom': 'Animar Zoom ao Passar o Mouse',
        'form.slider.v2.zoomLevel': 'Nível de Zoom',
        'form.slider.v2.zoomDuration': 'Duração do Zoom (s)',
        'form.slider.v2.section.export': 'Exportar',
        'form.slider.v2.beforeDestinationUrl': 'URL de Destino da Imagem "Antes"',
        'form.slider.v2.afterDestinationUrl': 'URL de Destino da Imagem "Depois"',
        'form.slider.v2.exportHtml': 'Exportar HTML para GAM/DV360',
        'form.slider.v2.exportGif': 'Exportar GIF de Demonstração',
        'form.soccer.section.general': 'Configurações Gerais',
        'form.soccer.section.assets': 'Recursos',
        'form.soccer.videoUrl': 'URL do Vídeo',
        'form.soccer.uploadVideo': 'Carregar Vídeo',
        'form.soccer.imageUrl': 'URL da Imagem',
        'form.soccer.uploadImage': 'Carregar Imagem',
        'form.soccer.imageHint': 'Tamanho de imagem recomendado: {size}',
        'form.soccer.exportHtml_dv360': 'Exportar ZIP para DV360',
        'form.soccer.exportHtml_gam': 'Exportar HTML para GAM',
        'form.carousel.section.general': 'Configurações Gerais',
        'form.carousel.ctaText': 'Texto do Botão CTA',
        'form.carousel.ctaBgColor': 'Cor de Fundo do CTA',
        'form.carousel.ctaColor': 'Cor do Texto do CTA',
        'form.carousel.progressBarColor': 'Cor da Barra de Progresso',
        'form.carousel.autoPlay': 'Reprodução Automática dos Slides',
        'form.carousel.playDuration': 'Duração da Reprodução (s)',
        'form.carousel.section.slides': 'Slides',
        'form.carousel.addSlide': 'Adicionar Novo Slide',
        'form.carousel.slide': 'Slide',
        'form.carousel.headline': 'Título',
        'form.carousel.caption': 'Legenda',
        'form.carousel.exportHtml': 'Exportar HTML para GAM/DV360',
        'form.cube.section.general': 'Configurações Gerais',
        'form.cube.frontImage': 'Imagem da Face Frontal',
        'form.cube.sideImage': 'Imagem da Face Lateral',
        'form.cube.uploadImage': 'Carregar Imagem',
        'form.cube.rotationSpeed': 'Velocidade de Rotação (segundos)',
        'form.cube.exportHtml': 'Exportar Apenas HTML (Links CDN)',
        'form.cube.exportZip': 'Exportar ZIP (HTML + Imagens)',
    }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    const langData = languageData[language] as Record<string, string>;
    return langData[key] || key;
  };
  
  const value = useMemo(() => ({ language, setLanguage, t }), [language]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};